export const fake_trending = [
    {
        "adult": false,
        "backdrop_path": "/lsN1wAbqCvUPKEhkEI9pQSSiTjU.jpg",
        "id": 661374,
        "title": "Glass Onion: A Knives Out Mystery",
        "original_language": "en",
        "original_title": "Glass Onion: A Knives Out Mystery",
        "overview": "World-famous detective Benoit Blanc heads to Greece to peel back the layers of a mystery surrounding a tech billionaire and his eclectic crew of friends.",
        "poster_path": "/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg",
        "media_type": "movie",
        "genre_ids": [
            9648,
            53,
            35
        ],
        "popularity": 4858.378,
        "release_date": "2022-11-23",
        "video": false,
        "vote_average": 7.051,
        "vote_count": 1770
    },
    {
        "adult": false,
        "backdrop_path": "/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
        "id": 76600,
        "title": "Avatar: The Way of Water",
        "original_language": "en",
        "original_title": "Avatar: The Way of Water",
        "overview": "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
        "poster_path": "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
        "media_type": "movie",
        "genre_ids": [
            878,
            12,
            28
        ],
        "popularity": 5896.522,
        "release_date": "2022-12-14",
        "video": false,
        "vote_average": 7.695,
        "vote_count": 3272
    },
    {
        "adult": false,
        "backdrop_path": "/eLmA7Lw0EnXM8baIxbhyuzM37jP.jpg",
        "id": 744594,
        "title": "White Noise",
        "original_language": "en",
        "original_title": "White Noise",
        "overview": "Jack Gladney, professor of Hitler studies at The-College-on-the-Hill, husband to Babette, and father to four children/stepchildren, is torn asunder by a chemical spill from a rail car that releases an \"Airborne Toxic Event\" forcing Jack to confront his biggest fear - his own mortality.",
        "poster_path": "/sXFRM14wo5zHFDqqC0QtW7Qy4vL.jpg",
        "media_type": "movie",
        "genre_ids": [
            35,
            18,
            878
        ],
        "popularity": 59.024,
        "release_date": "2022-11-25",
        "video": false,
        "vote_average": 5.625,
        "vote_count": 80
    },
    {
        "adult": false,
        "backdrop_path": "/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg",
        "id": 361743,
        "title": "Top Gun: Maverick",
        "original_language": "en",
        "original_title": "Top Gun: Maverick",
        "overview": "After more than thirty years of service as one of the Navy’s top aviators, and dodging the advancement in rank that would ground him, Pete “Maverick” Mitchell finds himself training a detachment of TOP GUN graduates for a specialized mission the likes of which no living pilot has ever seen.",
        "poster_path": "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
        "media_type": "movie",
        "genre_ids": [
            28,
            18
        ],
        "popularity": 889.772,
        "release_date": "2022-05-24",
        "video": false,
        "vote_average": 8.338,
        "vote_count": 5349
    },
    {
        "adult": false,
        "backdrop_path": "/5wDBVictj4wUYZ31gR5WzCM9dLD.jpg",
        "id": 877269,
        "title": "Strange World",
        "original_language": "en",
        "original_title": "Strange World",
        "overview": "A journey deep into an uncharted and treacherous land, where fantastical creatures await the legendary Clades—a family of explorers whose differences threaten to topple their latest, and by far most crucial, mission.",
        "poster_path": "/jXGMJUq9zcrScs02qkQuCtmWwaI.jpg",
        "media_type": "movie",
        "genre_ids": [
            16,
            878,
            12,
            10751
        ],
        "popularity": 1787.414,
        "release_date": "2022-11-23",
        "video": false,
        "vote_average": 6.532,
        "vote_count": 349
    },
    {
        "adult": false,
        "backdrop_path": "/bQXAqRx2Fgc46uCVWgoPz5L5Dtr.jpg",
        "id": 436270,
        "title": "Black Adam",
        "original_language": "en",
        "original_title": "Black Adam",
        "overview": "Nearly 5,000 years after he was bestowed with the almighty powers of the Egyptian gods—and imprisoned just as quickly—Black Adam is freed from his earthly tomb, ready to unleash his unique form of justice on the modern world.",
        "poster_path": "/pFlaoHTZeyNkG83vxsAJiGzfSsa.jpg",
        "media_type": "movie",
        "genre_ids": [
            28,
            14,
            878
        ],
        "popularity": 3282.638,
        "release_date": "2022-10-19",
        "video": false,
        "vote_average": 7.219,
        "vote_count": 3427
    },
    {
        "adult": false,
        "backdrop_path": "/jG52tsazn04F1fe8hPZfVv7ICKt.jpg",
        "id": 668482,
        "title": "Roald Dahl's Matilda the Musical",
        "original_language": "en",
        "original_title": "Roald Dahl's Matilda the Musical",
        "overview": "An extraordinary young girl discovers her superpower and summons the remarkable courage, against all odds, to help others change their stories, whilst also taking charge of her own destiny. Standing up for what's right, she's met with miraculous results.",
        "poster_path": "/ga8R3OiOMMgSvZ4cOj8x7prUNYZ.jpg",
        "media_type": "movie",
        "genre_ids": [
            10751,
            35,
            14
        ],
        "popularity": 586.583,
        "release_date": "2022-11-25",
        "video": false,
        "vote_average": 6.869,
        "vote_count": 175
    },
    {
        "adult": false,
        "backdrop_path": "/o0s4XsEDfDlvit5pDRKjzXR4pp2.jpg",
        "id": 19995,
        "title": "Avatar",
        "original_language": "en",
        "original_title": "Avatar",
        "overview": "In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",
        "poster_path": "/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg",
        "media_type": "movie",
        "genre_ids": [
            28,
            12,
            14,
            878
        ],
        "popularity": 3058.736,
        "release_date": "2009-12-15",
        "video": false,
        "vote_average": 7.554,
        "vote_count": 27415
    },
    {
        "adult": false,
        "backdrop_path": "/tt79dbOPd9Z9ykEOpvckttgYXwH.jpg",
        "id": 545611,
        "title": "Everything Everywhere All at Once",
        "original_language": "en",
        "original_title": "Everything Everywhere All at Once",
        "overview": "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
        "poster_path": "/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
        "media_type": "movie",
        "genre_ids": [
            28,
            12,
            878
        ],
        "popularity": 256.017,
        "release_date": "2022-03-24",
        "video": false,
        "vote_average": 8.086,
        "vote_count": 2510
    },
    {
        "adult": false,
        "backdrop_path": "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
        "id": 505642,
        "title": "Black Panther: Wakanda Forever",
        "original_language": "en",
        "original_title": "Black Panther: Wakanda Forever",
        "overview": "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
        "poster_path": "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
        "media_type": "movie",
        "genre_ids": [
            28,
            12,
            878
        ],
        "popularity": 1524.924,
        "release_date": "2022-11-09",
        "video": false,
        "vote_average": 7.491,
        "vote_count": 1526
    },
    {
        "adult": false,
        "backdrop_path": "/6mEYUYdkKoVCMeYf3rTFj0L1uyv.jpg",
        "id": 899112,
        "title": "Violent Night",
        "original_language": "en",
        "original_title": "Violent Night",
        "overview": "When a team of mercenaries breaks into a wealthy family compound on Christmas Eve, taking everyone inside hostage, the team isn’t prepared for a surprise combatant: Santa Claus is on the grounds, and he’s about to show why this Nick is no saint.",
        "poster_path": "/1XSYOP0JjjyMz1irihvWywro82r.jpg",
        "media_type": "movie",
        "genre_ids": [
            28,
            35,
            80,
            53
        ],
        "popularity": 4746.942,
        "release_date": "2022-11-30",
        "video": false,
        "vote_average": 7.717,
        "vote_count": 695
    },
    {
        "adult": false,
        "backdrop_path": "/2JeIqOdSM5nC1SQmuhUOfj3iB1U.jpg",
        "id": 555604,
        "title": "Guillermo del Toro's Pinocchio",
        "original_language": "en",
        "original_title": "Guillermo del Toro's Pinocchio",
        "overview": "During the rise of fascism in Mussolini's Italy, a wooden boy brought magically to life struggles to live up to his father's expectations.",
        "poster_path": "/vx1u0uwxdlhV2MUzj4VlcMB0N6m.jpg",
        "media_type": "movie",
        "genre_ids": [
            16,
            14,
            18
        ],
        "popularity": 1659.282,
        "release_date": "2022-11-09",
        "video": false,
        "vote_average": 8.43,
        "vote_count": 1267
    },
    {
        "adult": false,
        "backdrop_path": "/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
        "id": 414906,
        "title": "The Batman",
        "original_language": "en",
        "original_title": "The Batman",
        "overview": "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
        "poster_path": "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
        "media_type": "movie",
        "genre_ids": [
            80,
            9648,
            53
        ],
        "popularity": 390.709,
        "release_date": "2022-03-01",
        "video": false,
        "vote_average": 7.707,
        "vote_count": 7094
    },
    {
        "adult": false,
        "backdrop_path": "/9Md4CqzUGDtK5oEkRRvozLkGc9d.jpg",
        "id": 674324,
        "title": "The Banshees of Inisherin",
        "original_language": "en",
        "original_title": "The Banshees of Inisherin",
        "overview": "Two lifelong friends find themselves at an impasse when one abruptly ends their relationship, with alarming consequences for both of them.",
        "poster_path": "/4yFG6cSPaCaPhyJ1vtGOtMD1lgh.jpg",
        "media_type": "movie",
        "genre_ids": [
            18,
            35
        ],
        "popularity": 317.242,
        "release_date": "2022-10-21",
        "video": false,
        "vote_average": 7.594,
        "vote_count": 302
    },
    {
        "adult": false,
        "backdrop_path": "/vNPY4oCSUp7CxbHkKJNRx1fmCl0.jpg",
        "id": 497828,
        "title": "Triangle of Sadness",
        "original_language": "en",
        "original_title": "Triangle of Sadness",
        "overview": "A celebrity model couple are invited on a luxury cruise for the uber-rich, helmed by an unhinged captain. What first appeared Instagrammable ends catastrophically, leaving the survivors stranded on a desert island and fighting for survival.",
        "poster_path": "/fgy78BLl0gk8OzTWHZyGrSlIEON.jpg",
        "media_type": "movie",
        "genre_ids": [
            35,
            18
        ],
        "popularity": 89.489,
        "release_date": "2022-09-23",
        "video": false,
        "vote_average": 7.6,
        "vote_count": 478
    },
    {
        "adult": false,
        "backdrop_path": "/fsTJDKNAhF9QptmGvON8hSOUyWi.jpg",
        "id": 890541,
        "title": "7 Women and a Murder",
        "original_language": "it",
        "original_title": "7 donne e un mistero",
        "overview": "When their family patriarch is stabbed, seven women, each with ulterior motives, become trapped together in a mansion to solve the puzzle of his murder. This is the  Italian remake of François Ozon's 8 Women.",
        "poster_path": "/iz2tpJJgSDBS646VYhmNkUmot4l.jpg",
        "media_type": "movie",
        "genre_ids": [
            9648,
            35
        ],
        "popularity": 34.635,
        "release_date": "2021-12-25",
        "video": false,
        "vote_average": 5.57,
        "vote_count": 100
    },
    {
        "adult": false,
        "backdrop_path": "/r9PkFnRUIthgBp2JZZzD380MWZy.jpg",
        "id": 315162,
        "title": "Puss in Boots: The Last Wish",
        "original_language": "en",
        "original_title": "Puss in Boots: The Last Wish",
        "overview": "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
        "poster_path": "/lmf0zzR7ritjOL3qumRh3hfvOFK.jpg",
        "media_type": "movie",
        "genre_ids": [
            16,
            12,
            35,
            10751,
            14
        ],
        "popularity": 1298.815,
        "release_date": "2022-12-07",
        "video": false,
        "vote_average": 7.948,
        "vote_count": 154
    },
    {
        "adult": false,
        "backdrop_path": "/x1VhwiNjr1dD0s5PT2iYvvOh2Op.jpg",
        "id": 762504,
        "title": "Nope",
        "original_language": "en",
        "original_title": "Nope",
        "overview": "Residents in a lonely gulch of inland California bear witness to an uncanny, chilling discovery.",
        "poster_path": "/AcKVlWaNVVVFQwro3nLXqPljcYA.jpg",
        "media_type": "movie",
        "genre_ids": [
            27,
            9648,
            878,
            53
        ],
        "popularity": 165.613,
        "release_date": "2022-07-20",
        "video": false,
        "vote_average": 6.937,
        "vote_count": 2276
    },
    {
        "adult": false,
        "backdrop_path": "/6RCf9jzKxyjblYV4CseayK6bcJo.jpg",
        "id": 804095,
        "title": "The Fabelmans",
        "original_language": "en",
        "original_title": "The Fabelmans",
        "overview": "Growing up in post-World War II era Arizona, young Sammy Fabelman aspires to become a filmmaker as he reaches adolescence, but soon discovers a shattering family secret and explores how the power of films can help him see the truth.",
        "poster_path": "/xId9zoiv5WPQOuxqykUDrlpmrUz.jpg",
        "media_type": "movie",
        "genre_ids": [
            18
        ],
        "popularity": 275.034,
        "release_date": "2022-11-11",
        "video": false,
        "vote_average": 8,
        "vote_count": 282
    },
    {
        "adult": false,
        "backdrop_path": "/6T0ioZM9ZyXXLBhcUixLJpN4q9i.jpg",
        "id": 536554,
        "title": "M3GAN",
        "original_language": "en",
        "original_title": "M3GAN",
        "overview": "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
        "poster_path": "/7CNCv9uhqdwK7Fv4bR4nmDysnd9.jpg",
        "media_type": "movie",
        "genre_ids": [
            27,
            878,
            53
        ],
        "popularity": 779.249,
        "release_date": "2023-01-04",
        "video": false,
        "vote_average": 6.611,
        "vote_count": 27
    }
]

export const fake_featured = {
	"adult": false,
	"backdrop_path": "/tyNqJUWqqb0tjhqXYH4uwRwsp6A.jpg",
	"belongs_to_collection": null,
	"budget": 35000000,
	"genres": [
		{
			"id": 16,
			"name": "Animation"
		},
		{
			"id": 14,
			"name": "Fantasy"
		},
		{
			"id": 18,
			"name": "Drama"
		}
	],
	"homepage": "https://www.netflix.com/title/80218455",
	"id": 555604,
	"imdb_id": "tt1488589",
	"original_language": "en",
	"original_title": "Guillermo del Toro's Pinocchio",
	"overview": "During the rise of fascism in Mussolini's Italy, a wooden boy brought magically to life struggles to live up to his father's expectations.",
	"popularity": 1350.725,
	"poster_path": "/vx1u0uwxdlhV2MUzj4VlcMB0N6m.jpg",
	"production_companies": [
		{
			"id": 6254,
			"logo_path": "/dHfP8fUyykmTsMXbtXO0kSsYz5E.png",
			"name": "The Jim Henson Company",
			"origin_country": "US"
		},
		{
			"id": 81667,
			"logo_path": null,
			"name": "ShadowMachine",
			"origin_country": "US"
		},
		{
			"id": 101082,
			"logo_path": null,
			"name": "Double Dare You Productions",
			"origin_country": "US"
		}
	],
	"production_countries": [
		{
			"iso_3166_1": "US",
			"name": "United States of America"
		}
	],
	"release_date": "2022-11-09",
	"revenue": 0,
	"runtime": 117,
	"spoken_languages": [
		{
			"english_name": "Italian",
			"iso_639_1": "it",
			"name": "Italiano"
		},
		{
			"english_name": "English",
			"iso_639_1": "en",
			"name": "English"
		}
	],
	"status": "Released",
	"tagline": "Love will give you life.",
	"title": "Guillermo del Toro's Pinocchio",
	"video": false,
	"vote_average": 8.399,
	"vote_count": 1377,
	"recommendations": {
		"page": 1,
		"results": [
			{
				"adult": false,
				"backdrop_path": "/atmII0hn3iQe3IWMBmIb3cc8EJZ.jpg",
				"id": 791177,
				"title": "Bones and All",
				"original_language": "en",
				"original_title": "Bones and All",
				"overview": "Abandoned by her father, a young woman embarks on a thousand-mile odyssey through the backroads of America where she meets a disenfranchised drifter. But despite their best efforts, all roads lead back to their terrifying pasts and to a final stand that will determine whether their love can survive their otherness.",
				"poster_path": "/gH6ppXl2gd1VMKoccKbLK69ZHQq.jpg",
				"media_type": "movie",
				"genre_ids": [
					18,
					27,
					10749
				],
				"popularity": 218.639,
				"release_date": "2022-11-18",
				"video": false,
				"vote_average": 7.487,
				"vote_count": 479
			},
			{
				"adult": false,
				"backdrop_path": "/nJbWAc8wakV3BncyF4643SyFWPr.jpg",
				"id": 774752,
				"title": "The Guardians of the Galaxy Holiday Special",
				"original_language": "en",
				"original_title": "The Guardians of the Galaxy Holiday Special",
				"overview": "On a mission to make Christmas unforgettable for Quill, the Guardians head to Earth in search of the perfect present.",
				"poster_path": "/8dqXyslZ2hv49Oiob9UjlGSHSTR.jpg",
				"media_type": "movie",
				"genre_ids": [
					35,
					878,
					12
				],
				"popularity": 402.448,
				"release_date": "2022-11-25",
				"video": false,
				"vote_average": 7.42,
				"vote_count": 996
			},
			{
				"adult": false,
				"backdrop_path": "/mSyQoValhBsJdq3JNGXJww2Q5yL.jpg",
				"id": 593643,
				"title": "The Menu",
				"original_language": "en",
				"original_title": "The Menu",
				"overview": "A couple travels to a coastal island to eat at an exclusive restaurant where the chef has prepared a lavish menu, with some shocking surprises.",
				"poster_path": "/fPtUgMcLIboqlTlPrq0bQpKK8eq.jpg",
				"media_type": "movie",
				"genre_ids": [
					53,
					27,
					35
				],
				"popularity": 612.165,
				"release_date": "2022-11-17",
				"video": false,
				"vote_average": 7.295,
				"vote_count": 787
			},
			{
				"adult": false,
				"backdrop_path": "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
				"id": 505642,
				"title": "Black Panther: Wakanda Forever",
				"original_language": "en",
				"original_title": "Black Panther: Wakanda Forever",
				"overview": "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death. As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
				"poster_path": "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
				"media_type": "movie",
				"genre_ids": [
					28,
					12,
					878
				],
				"popularity": 1356.206,
				"release_date": "2022-11-09",
				"video": false,
				"vote_average": 7.492,
				"vote_count": 1565
			},
			{
				"adult": false,
				"backdrop_path": "/s5MLcxbdFqvIzTLNLU5yQFFYALR.jpg",
				"id": 744114,
				"title": "My Policeman",
				"original_language": "en",
				"original_title": "My Policeman",
				"overview": "In the late 1990s, the arrival of elderly invalid Patrick into Marion and Tom’s home triggers the exploration of seismic events from 40 years previous: the passionate relationship between Tom and Patrick at a time when homosexuality was illegal.",
				"poster_path": "/wdbiMjXd4CxPfCx4r4Jfy8cGec0.jpg",
				"media_type": "movie",
				"genre_ids": [
					18,
					10749
				],
				"popularity": 44.938,
				"release_date": "2022-10-21",
				"video": false,
				"vote_average": 7.952,
				"vote_count": 393
			},
			{
				"adult": false,
				"backdrop_path": "/dKqa850uvbNSCaQCV4Im1XlzEtQ.jpg",
				"id": 661374,
				"title": "Glass Onion: A Knives Out Mystery",
				"original_language": "en",
				"original_title": "Glass Onion: A Knives Out Mystery",
				"overview": "World-famous detective Benoit Blanc heads to Greece to peel back the layers of a mystery surrounding a tech billionaire and his eclectic crew of friends.",
				"poster_path": "/vDGr1YdrlfbU9wxTOdpf3zChmv9.jpg",
				"media_type": "movie",
				"genre_ids": [
					9648,
					53,
					35
				],
				"popularity": 3751.901,
				"release_date": "2022-11-23",
				"video": false,
				"vote_average": 7.087,
				"vote_count": 2174
			}
		],
		"total_pages": 1,
		"total_results": 6
	},
	"credits": {
		"cast": [
			{
				"adult": false,
				"gender": 2,
				"id": 2099810,
				"known_for_department": "Acting",
				"name": "Gregory Mann",
				"original_name": "Gregory Mann",
				"popularity": 47.888,
				"profile_path": "/bGPUEFO6lCpxTvWn43fPSep4dtS.jpg",
				"cast_id": 26,
				"character": "Pinocchio (voice)",
				"credit_id": "5f3d4eb49ae6130035461a9f",
				"order": 0
			},
			{
				"adult": false,
				"gender": 2,
				"id": 3061,
				"known_for_department": "Acting",
				"name": "Ewan McGregor",
				"original_name": "Ewan McGregor",
				"popularity": 36.254,
				"profile_path": "/aEmyadfRXTmmR7UW7OXsm5a6smS.jpg",
				"cast_id": 21,
				"character": "Sebastian J. Cricket (voice)",
				"credit_id": "5e474cc0676ce2001afcb571",
				"order": 1
			},
			{
				"adult": false,
				"gender": 2,
				"id": 11180,
				"known_for_department": "Acting",
				"name": "David Bradley",
				"original_name": "David Bradley",
				"popularity": 15.249,
				"profile_path": "/znpkwHitb3pcaJbUmgDqG0YenYp.jpg",
				"cast_id": 18,
				"character": "Geppetto (voice)",
				"credit_id": "5e474c84676ce20013fc969d",
				"order": 2
			},
			{
				"adult": false,
				"gender": 2,
				"id": 27319,
				"known_for_department": "Acting",
				"name": "Christoph Waltz",
				"original_name": "Christoph Waltz",
				"popularity": 12.939,
				"profile_path": "/2Hhztd4mUEV9Y25rfkXDwzL9QI9.jpg",
				"cast_id": 22,
				"character": "Count Volpe (voice)",
				"credit_id": "5e474cd62d93750017a52674",
				"order": 3
			},
			{
				"adult": false,
				"gender": 1,
				"id": 3063,
				"known_for_department": "Acting",
				"name": "Tilda Swinton",
				"original_name": "Tilda Swinton",
				"popularity": 41.505,
				"profile_path": "/gWbX3a7V2MgRMRzekfITNcb27xV.jpg",
				"cast_id": 20,
				"character": "Wood Sprite / Death (voice)",
				"credit_id": "5e474cae2d93750017a525f2",
				"order": 4
			},
			{
				"adult": false,
				"gender": 2,
				"id": 2372,
				"known_for_department": "Acting",
				"name": "Ron Perlman",
				"original_name": "Ron Perlman",
				"popularity": 36.632,
				"profile_path": "/nfky6J9ueey1gMdWMNU9k9YdfGP.jpg",
				"cast_id": 19,
				"character": "Il Podestà (voice)",
				"credit_id": "5e474ca22d93750017a525c8",
				"order": 5
			},
			{
				"adult": false,
				"gender": 2,
				"id": 1442069,
				"known_for_department": "Acting",
				"name": "Finn Wolfhard",
				"original_name": "Finn Wolfhard",
				"popularity": 32.99,
				"profile_path": "/5OVmquAk0W5BIsRlVKslEP497JD.jpg",
				"cast_id": 24,
				"character": "Candlewick (voice)",
				"credit_id": "5f3d3fbb9ae613003645819a",
				"order": 6
			},
			{
				"adult": false,
				"gender": 1,
				"id": 112,
				"known_for_department": "Acting",
				"name": "Cate Blanchett",
				"original_name": "Cate Blanchett",
				"popularity": 42.361,
				"profile_path": "/vUuEHiAR0eD3XEJhg2DWIjymUAA.jpg",
				"cast_id": 23,
				"character": "Spazzatura the Monkey (voice)",
				"credit_id": "5f3d3f3f35a61e0035f79703",
				"order": 7
			},
			{
				"adult": false,
				"gender": 2,
				"id": 1462,
				"known_for_department": "Acting",
				"name": "Tim Blake Nelson",
				"original_name": "Tim Blake Nelson",
				"popularity": 15.569,
				"profile_path": "/rWuTGiAMaaHIJ30eRkQS23LbRSW.jpg",
				"cast_id": 25,
				"character": "The Black Rabbits (voice)",
				"credit_id": "5f3d4249afe22400336f12a9",
				"order": 8
			},
			{
				"adult": false,
				"gender": 2,
				"id": 1241,
				"known_for_department": "Acting",
				"name": "John Turturro",
				"original_name": "John Turturro",
				"popularity": 26.202,
				"profile_path": "/6O9W9cJW0kCqMzYeLupV9oH0ftn.jpg",
				"cast_id": 27,
				"character": "Il Dottore (voice)",
				"credit_id": "5f3d4ee52da8460031c6e98e",
				"order": 9
			},
			{
				"adult": false,
				"gender": 2,
				"id": 39659,
				"known_for_department": "Acting",
				"name": "Burn Gorman",
				"original_name": "Burn Gorman",
				"popularity": 9.079,
				"profile_path": "/31IjmuR91tpXdBMI714ap1MAVLv.jpg",
				"cast_id": 28,
				"character": "Priest (voice)",
				"credit_id": "5f3d4ef235a61e0036f912b9",
				"order": 10
			},
			{
				"adult": false,
				"gender": 2,
				"id": 78798,
				"known_for_department": "Acting",
				"name": "Tom Kenny",
				"original_name": "Tom Kenny",
				"popularity": 21.903,
				"profile_path": "/kftXtExrcoTTjyeYmSXJ0Ogr3R7.jpg",
				"cast_id": 57,
				"character": "Mussolini / Right Hand Man / Sea Captain (voice)",
				"credit_id": "638d28967d5db50fbf010a33",
				"order": 11
			},
			{
				"adult": false,
				"gender": 0,
				"id": 3815640,
				"known_for_department": "Acting",
				"name": "Alfie Tempest",
				"original_name": "Alfie Tempest",
				"popularity": 0.6,
				"profile_path": "/4nkoNuusnc5cIwxlPnEQ9WmIYZZ.jpg",
				"cast_id": 58,
				"character": "Carlo (voice)",
				"credit_id": "638d28bb15376c3d9ae1892a",
				"order": 12
			},
			{
				"adult": false,
				"gender": 1,
				"id": 3815645,
				"known_for_department": "Acting",
				"name": "Anthea Greco",
				"original_name": "Anthea Greco",
				"popularity": 0.6,
				"profile_path": "/auBdznWStcdZwv7vNIstHduTzKf.jpg",
				"cast_id": 59,
				"character": "Podestà's Wife / Twin Daughter 1  (voice)",
				"credit_id": "638d29351283e900861f67ec",
				"order": 13
			},
			{
				"adult": false,
				"gender": 1,
				"id": 1591205,
				"known_for_department": "Acting",
				"name": "Francesca Fanti",
				"original_name": "Francesca Fanti",
				"popularity": 0.949,
				"profile_path": "/8Kti1mECLgP1QYmkSiDl3EOsCxE.jpg",
				"cast_id": 60,
				"character": "Twin Daughter 2 / Old Woman / Street Sweep (voice)",
				"credit_id": "638d297915376c3e0ff3f666",
				"order": 14
			},
			{
				"adult": false,
				"gender": 0,
				"id": 3815647,
				"known_for_department": "Acting",
				"name": "Sandro Carotti",
				"original_name": "Sandro Carotti",
				"popularity": 0.6,
				"profile_path": null,
				"cast_id": 61,
				"character": "Fruit Vendor / Butcher (voice)",
				"credit_id": "638d299115376c3da2228caa",
				"order": 15
			},
			{
				"adult": false,
				"gender": 2,
				"id": 1298900,
				"known_for_department": "Acting",
				"name": "Rio Mangini",
				"original_name": "Rio Mangini",
				"popularity": 4.419,
				"profile_path": "/qDW77edoCKRBzM3hH111RneRYB4.jpg",
				"cast_id": 62,
				"character": "Milliner / Soldier / Carnival Worker (voice)",
				"credit_id": "638d29a20e64af00adab15cf",
				"order": 16
			},
			{
				"adult": false,
				"gender": 2,
				"id": 2623517,
				"known_for_department": "Acting",
				"name": "Benjamin Valic",
				"original_name": "Benjamin Valic",
				"popularity": 1.238,
				"profile_path": "/vpedWcdmhA9Fa6SiRDD7IKwgDey.jpg",
				"cast_id": 63,
				"character": "Confident Boy / Laughing Boy (voice)",
				"credit_id": "638d29b00e64af00c25e21a0",
				"order": 17
			},
			{
				"adult": false,
				"gender": 1,
				"id": 2405433,
				"known_for_department": "Acting",
				"name": "Sky Alexis",
				"original_name": "Sky Alexis",
				"popularity": 0.773,
				"profile_path": "/z1tEwgQFrLWF9lCDAugpN0yNSS4.jpg",
				"cast_id": 64,
				"character": "Young Girl (voice)",
				"credit_id": "638d29d8c3aa3f007f35c42b",
				"order": 18
			},
			{
				"adult": false,
				"gender": 0,
				"id": 1393238,
				"known_for_department": "Acting",
				"name": "Ariana Molkara",
				"original_name": "Ariana Molkara",
				"popularity": 2.763,
				"profile_path": "/iiCKWn09sAziALHkE519xw3zyEe.jpg",
				"cast_id": 65,
				"character": "Older Girl (voice)",
				"credit_id": "638d29e87d5db50fb78c55a9",
				"order": 19
			},
			{
				"adult": false,
				"gender": 0,
				"id": 3806714,
				"known_for_department": "Acting",
				"name": "Roy Halo",
				"original_name": "Roy Halo",
				"popularity": 0.6,
				"profile_path": null,
				"cast_id": 66,
				"character": "Young Boy (voice)",
				"credit_id": "638d2a1215376c3daaf94b31",
				"order": 20
			},
			{
				"adult": false,
				"gender": 0,
				"id": 3815649,
				"known_for_department": "Acting",
				"name": "Luciano Palmeri",
				"original_name": "Luciano Palmeri",
				"popularity": 0.6,
				"profile_path": null,
				"cast_id": 67,
				"character": "Barrel Man / Soldier / Carnival Worker (voice)",
				"credit_id": "638d2a262dc9dc0084e70323",
				"order": 21
			},
			{
				"adult": false,
				"gender": 2,
				"id": 1585749,
				"known_for_department": "Acting",
				"name": "Peter Arpesella",
				"original_name": "Peter Arpesella",
				"popularity": 1.361,
				"profile_path": "/7GuaSB2xa6m0DpBtaO6uGSlnZBh.jpg",
				"cast_id": 68,
				"character": "Carnival Worker (voice)",
				"credit_id": "638d2a397d5db5101e5639d9",
				"order": 22
			}
		],
		"crew": [
			{
				"adult": false,
				"gender": 2,
				"id": 2949,
				"known_for_department": "Sound",
				"name": "Alexandre Desplat",
				"original_name": "Alexandre Desplat",
				"popularity": 2.353,
				"profile_path": "/vPsv5UYNLrQkzjOvng1OAAYCTIz.jpg",
				"credit_id": "5f3d50099590e3003571f6e5",
				"department": "Sound",
				"job": "Original Music Composer"
			},
			{
				"adult": false,
				"gender": 2,
				"id": 3193,
				"known_for_department": "Sound",
				"name": "Scott Martin Gershin",
				"original_name": "Scott Martin Gershin",
				"popularity": 3.478,
				"profile_path": null,
				"credit_id": "61c8ebcfbb1057001ac46e0f",
				"department": "Sound",
				"job": "Sound Supervisor"
			},
			{
				"adult": false,
				"gender": 1,
				"id": 7903,
				"known_for_department": "Production",
				"name": "Mary Hidalgo",
				"original_name": "Mary Hidalgo",
				"popularity": 3.367,
				"profile_path": null,
				"credit_id": "6375a92d11c066007b126bf6",
				"department": "Production",
				"job": "Casting Director"
			},
			{
				"adult": false,
				"gender": 2,
				"id": 8063,
				"known_for_department": "Editing",
				"name": "Ken Schretzmann",
				"original_name": "Ken Schretzmann",
				"popularity": 2.183,
				"profile_path": null,
				"credit_id": "5fe7c0de07a80800408aba81",
				"department": "Editing",
				"job": "Editor"
			},
			{
				"adult": false,
				"gender": 2,
				"id": 12677,
				"known_for_department": "Writing",
				"name": "Matthew Robbins",
				"original_name": "Matthew Robbins",
				"popularity": 3.171,
				"profile_path": "/abxZZtYWLhnliR572pJvhfyksnD.jpg",
				"credit_id": "639567cf8a88b2008a2feb39",
				"department": "Writing",
				"job": "Screenstory"
			},
			{
				"adult": false,
				"gender": 2,
				"id": 10828,
				"known_for_department": "Directing",
				"name": "Guillermo del Toro",
				"original_name": "Guillermo del Toro",
				"popularity": 17.156,
				"profile_path": "/gldeyCtKcaqnK1v4Vu9vqayhzUQ.jpg",
				"credit_id": "5bcde47b0e0a26016402481b",
				"department": "Writing",
				"job": "Screenplay"
			},
			{
				"adult": false,
				"gender": 2,
				"id": 10828,
				"known_for_department": "Directing",
				"name": "Guillermo del Toro",
				"original_name": "Guillermo del Toro",
				"popularity": 17.156,
				"profile_path": "/gldeyCtKcaqnK1v4Vu9vqayhzUQ.jpg",
				"credit_id": "5bcde463925141613e020c2e",
				"department": "Directing",
				"job": "Director"
			},
			{
				"adult": false,
				"gender": 2,
				"id": 10828,
				"known_for_department": "Directing",
				"name": "Guillermo del Toro",
				"original_name": "Guillermo del Toro",
				"popularity": 17.156,
				"profile_path": "/gldeyCtKcaqnK1v4Vu9vqayhzUQ.jpg",
				"credit_id": "5bcde46d9251416131023f7d",
				"department": "Production",
				"job": "Producer"
			},
			{
				"adult": false,
				"gender": 2,
				"id": 10828,
				"known_for_department": "Directing",
				"name": "Guillermo del Toro",
				"original_name": "Guillermo del Toro",
				"popularity": 17.156,
				"profile_path": "/gldeyCtKcaqnK1v4Vu9vqayhzUQ.jpg",
				"credit_id": "639567b49f5dfb00b6aed7a3",
				"department": "Writing",
				"job": "Screenstory"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 40289,
				"known_for_department": "Production",
				"name": "Gary Ungar",
				"original_name": "Gary Ungar",
				"popularity": 0.833,
				"profile_path": null,
				"credit_id": "62e184fafe5c910054c23bb9",
				"department": "Production",
				"job": "Producer"
			},
			{
				"adult": false,
				"gender": 2,
				"id": 53332,
				"known_for_department": "Camera",
				"name": "Frank Passingham",
				"original_name": "Frank Passingham",
				"popularity": 1.998,
				"profile_path": "/sRJqbXJiiNkqWzFmyl1fxLpSnUp.jpg",
				"credit_id": "5f3d8c0f9715ae0036dfacab",
				"department": "Camera",
				"job": "Director of Photography"
			},
			{
				"adult": false,
				"gender": 2,
				"id": 67372,
				"known_for_department": "Writing",
				"name": "Carlo Collodi",
				"original_name": "Carlo Collodi",
				"popularity": 2.243,
				"profile_path": "/lBdW5aQERqJJygC8mVa6O7g06Zc.jpg",
				"credit_id": "6395677a9f5dfb00916d31ee",
				"department": "Writing",
				"job": "Book"
			},
			{
				"adult": false,
				"gender": 2,
				"id": 69089,
				"known_for_department": "Production",
				"name": "Alexander Bulkley",
				"original_name": "Alexander Bulkley",
				"popularity": 0.996,
				"profile_path": null,
				"credit_id": "5c02f7389251410b92097fba",
				"department": "Production",
				"job": "Producer"
			},
			{
				"adult": false,
				"gender": 2,
				"id": 69092,
				"known_for_department": "Production",
				"name": "Corey Campodonico",
				"original_name": "Corey Campodonico",
				"popularity": 0.644,
				"profile_path": null,
				"credit_id": "5c02f74ec3a36864760b8131",
				"department": "Production",
				"job": "Producer"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 93021,
				"known_for_department": "Production",
				"name": "Jason Lust",
				"original_name": "Jason Lust",
				"popularity": 0.631,
				"profile_path": null,
				"credit_id": "639568b5a0f1a200c8809f6f",
				"department": "Production",
				"job": "Executive Producer"
			},
			{
				"adult": false,
				"gender": 1,
				"id": 79666,
				"known_for_department": "Production",
				"name": "Lisa Henson",
				"original_name": "Lisa Henson",
				"popularity": 0.691,
				"profile_path": "/2TOZY4kMjn6dPRSbM4wX2MIBgTI.jpg",
				"credit_id": "5c02f7619251417e5504a220",
				"department": "Production",
				"job": "Producer"
			},
			{
				"adult": false,
				"gender": 1,
				"id": 92735,
				"known_for_department": "Production",
				"name": "Melanie Coombs",
				"original_name": "Melanie Coombs",
				"popularity": 0.794,
				"profile_path": null,
				"credit_id": "5fe7c1a1c9dbf9003b47693f",
				"department": "Production",
				"job": "Production Supervisor"
			},
			{
				"adult": false,
				"gender": 2,
				"id": 1245729,
				"known_for_department": "Writing",
				"name": "Patrick McHale",
				"original_name": "Patrick McHale",
				"popularity": 2.424,
				"profile_path": "/LI52FbJ23GnsPz6NExUJmSi0XS.jpg",
				"credit_id": "5bcde4be0e0a260162025dee",
				"department": "Writing",
				"job": "Screenplay"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 1245934,
				"known_for_department": "Directing",
				"name": "Mark Gustafson",
				"original_name": "Mark Gustafson",
				"popularity": 2.956,
				"profile_path": "/84ASwEwmYzbV6Yqp8Y539G16tif.jpg",
				"credit_id": "635c658ac9dbf900820a7f64",
				"department": "Directing",
				"job": "Director"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 1331976,
				"known_for_department": "Writing",
				"name": "Gris Grimly",
				"original_name": "Gris Grimly",
				"popularity": 0.77,
				"profile_path": null,
				"credit_id": "62e18519bbcae0005579bf30",
				"department": "Production",
				"job": "Co-Producer"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 1428471,
				"known_for_department": "Costume & Make-Up",
				"name": "Charmaine Fuller",
				"original_name": "Charmaine Fuller",
				"popularity": 0.6,
				"profile_path": null,
				"credit_id": "61c8ebabaaec71004029f336",
				"department": "Costume & Make-Up",
				"job": "Makeup Department Head"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 1448052,
				"known_for_department": "Visual Effects",
				"name": "Anthony Elworthy",
				"original_name": "Anthony Elworthy",
				"popularity": 0.698,
				"profile_path": null,
				"credit_id": "624a59975ff34e0063beb24c",
				"department": "Visual Effects",
				"job": "Lead Animator"
			},
			{
				"adult": false,
				"gender": 2,
				"id": 1448061,
				"known_for_department": "Visual Effects",
				"name": "Brian Leif Hansen",
				"original_name": "Brian Leif Hansen",
				"popularity": 1.312,
				"profile_path": null,
				"credit_id": "5f3d8bf9afe2240033705cae",
				"department": "Visual Effects",
				"job": "Animation Supervisor"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 1453551,
				"known_for_department": "Writing",
				"name": "Vera Brosgol",
				"original_name": "Vera Brosgol",
				"popularity": 1.073,
				"profile_path": null,
				"credit_id": "639f5ed32f3b1700ba03f3f8",
				"department": "Writing",
				"job": "Head of Story"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 1453594,
				"known_for_department": "Visual Effects",
				"name": "Chuck Duke",
				"original_name": "Chuck Duke",
				"popularity": 0.996,
				"profile_path": null,
				"credit_id": "624a59ada9117f00647c98f5",
				"department": "Visual Effects",
				"job": "Lead Animator"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 1453631,
				"known_for_department": "Visual Effects",
				"name": "Dan Ramsay",
				"original_name": "Dan Ramsay",
				"popularity": 0.6,
				"profile_path": null,
				"credit_id": "624a59bccb71b8009f78eefa",
				"department": "Visual Effects",
				"job": "Lead Animator"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 1455651,
				"known_for_department": "Art",
				"name": "Tennessee Reid Norton",
				"original_name": "Tennessee Reid Norton",
				"popularity": 0.6,
				"profile_path": null,
				"credit_id": "6399bf8ece9e910094b38c26",
				"department": "Visual Effects",
				"job": "Animation"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 1462578,
				"known_for_department": "Visual Effects",
				"name": "Sara Crowley",
				"original_name": "Sara Crowley",
				"popularity": 0.6,
				"profile_path": null,
				"credit_id": "5fe7c1b6cee48100402e0d35",
				"department": "Production",
				"job": "Production Manager"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 1634470,
				"known_for_department": "Sound",
				"name": "Steven Gizicki",
				"original_name": "Steven Gizicki",
				"popularity": 0.832,
				"profile_path": null,
				"credit_id": "6375a91bc6006d00aab12253",
				"department": "Sound",
				"job": "Music Supervisor"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 1674248,
				"known_for_department": "Art",
				"name": "Guy Davis",
				"original_name": "Guy Davis",
				"popularity": 1.169,
				"profile_path": null,
				"credit_id": "5bce08a1c3a3683d63000e4b",
				"department": "Art",
				"job": "Production Design"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 1683328,
				"known_for_department": "Production",
				"name": "Blanca Lista",
				"original_name": "Blanca Lista",
				"popularity": 0.6,
				"profile_path": null,
				"credit_id": "5c02f7969251417e5504a256",
				"department": "Production",
				"job": "Co-Producer"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 1687190,
				"known_for_department": "Art",
				"name": "Curt Enderle",
				"original_name": "Curt Enderle",
				"popularity": 0.6,
				"profile_path": null,
				"credit_id": "5f3d8bce9715ae0034df60e3",
				"department": "Art",
				"job": "Production Design"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 2011320,
				"known_for_department": "Art",
				"name": "Robert DeSue",
				"original_name": "Robert DeSue",
				"popularity": 0.6,
				"profile_path": null,
				"credit_id": "5f3d8c28e295b40033a44dc7",
				"department": "Art",
				"job": "Art Direction"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 2015715,
				"known_for_department": "Art",
				"name": "Andy Berry",
				"original_name": "Andy Berry",
				"popularity": 0.6,
				"profile_path": null,
				"credit_id": "5fe7c11dcee48100432c3e5e",
				"department": "Art",
				"job": "Assistant Art Director"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 2015717,
				"known_for_department": "Art",
				"name": "Jesse Gregg",
				"original_name": "Jesse Gregg",
				"popularity": 0.6,
				"profile_path": null,
				"credit_id": "5fe7c1391ac292003dbe90aa",
				"department": "Art",
				"job": "Set Decoration"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 2140216,
				"known_for_department": "Crew",
				"name": "Laura Savage",
				"original_name": "Laura Savage",
				"popularity": 0.6,
				"profile_path": null,
				"credit_id": "5fe7c1645b1240003d68c97c",
				"department": "Art",
				"job": "Set Decoration"
			},
			{
				"adult": false,
				"gender": 1,
				"id": 2194117,
				"known_for_department": "Production",
				"name": "Samantha Levine",
				"original_name": "Samantha Levine",
				"popularity": 1.22,
				"profile_path": "/e1kD0780tWsIsrBivAkkkKDBnZO.jpg",
				"credit_id": "61c8eb3ebe2d49001cc16328",
				"department": "Art",
				"job": "Set Decoration"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 3140650,
				"known_for_department": "Acting",
				"name": "Georgina Hayns",
				"original_name": "Georgina Hayns",
				"popularity": 0.6,
				"profile_path": null,
				"credit_id": "62e1859a47c9fb016aa813bb",
				"department": "Crew",
				"job": "Other"
			},
			{
				"adult": false,
				"gender": 0,
				"id": 3836261,
				"known_for_department": "Editing",
				"name": "Holly Klein",
				"original_name": "Holly Klein",
				"popularity": 0.6,
				"profile_path": null,
				"credit_id": "639f5f2b223e2000835a036b",
				"department": "Editing",
				"job": "Editor"
			}
		]
	}
}